# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_coreurl": "00_httpapi.ipynb",
         "add_items": "00_httpapi.ipynb",
         "get_items": "00_httpapi.ipynb",
         "cat": "00_httpapi.ipynb",
         "get_peers": "00_httpapi.ipynb",
         "find_dht_peer": "00_httpapi.ipynb",
         "find_value_provider": "00_httpapi.ipynb",
         "get_dht_value": "00_httpapi.ipynb",
         "block_get": "00_httpapi.ipynb",
         "block_put": "00_httpapi.ipynb",
         "block_rm": "00_httpapi.ipynb",
         "block_stat": "00_httpapi.ipynb",
         "est_get_public_stats": "estuaryapi.ipynb",
         "est_get_viewer": "estuaryapi.ipynb",
         "est_upload": "estuaryapi.ipynb",
         "est_list_data": "estuaryapi.ipynb",
         "est_create_collection": "estuaryapi.ipynb",
         "est_add_file_to_collection": "estuaryapi.ipynb",
         "list_pins": "estuaryapi.ipynb",
         "add_pin": "estuaryapi.ipynb",
         "get_pin": "estuaryapi.ipynb",
         "replace_pin": "estuaryapi.ipynb",
         "remove_pin": "estuaryapi.ipynb",
         "create_coll": "estuaryapi.ipynb",
         "add_content": "estuaryapi.ipynb",
         "list_colls": "estuaryapi.ipynb",
         "list_coll_content": "estuaryapi.ipynb",
         "list_content_path": "estuaryapi.ipynb",
         "add_content_path": "estuaryapi.ipynb",
         "add_key": "estuaryapi.ipynb",
         "add_data": "estuaryapi.ipynb",
         "add_cid": "estuaryapi.ipynb",
         "add_car": "estuaryapi.ipynb",
         "make_deal": "estuaryapi.ipynb",
         "add_data_cid": "estuaryapi.ipynb",
         "list_data": "estuaryapi.ipynb",
         "list_deals": "estuaryapi.ipynb",
         "get_deal_status": "estuaryapi.ipynb",
         "get_node_stats": "estuaryapi.ipynb",
         "get_deal_data": "estuaryapi.ipynb",
         "get_miner_ask": "estuaryapi.ipynb",
         "get_failure_logs": "estuaryapi.ipynb",
         "get_deal_logs": "estuaryapi.ipynb",
         "get_provider_stats": "estuaryapi.ipynb",
         "list_providers": "estuaryapi.ipynb"}

modules = ["httpapi.py",
           "estuaryapi.py"]

doc_url = "algoveraai.github.io/ipfspy//ipfspy/"

git_url = "https://github.com/AlgoveraAI/ipfspy/tree/master/"

def custom_doc_links(name): return None
