# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_utils.ipynb (unless otherwise specified).

__all__ = ['get_coreurl', 'parse_response']

# Cell
import requests
import json
from fastcore.all import *
import pandas as pd

# Cell
def get_coreurl(
    local:bool=True, # If local uses local node, else uses Infura.io gateway
):
    'Set the core url for convenience'
    if local:
        return f"http://127.0.0.1:5001/api/v0"
    else:
        return f"https://ipfs.infura.io:5001/api/v0"

# Cell
def parse_response(
    response, # Response object
):
    "Parse response object into JSON"

    if response.text.split('\n')[-1] == "":
        return [json.loads(each) for each in response.text.split('\n')[:-1]]

    else:
        return response.json()