FROM python:3.8.2-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Install linux dependencies
RUN apt-get update && \
    apt-get upgrade -y
# RUN apt-get install -y libssl-dev
# RUN apt-get install -y gcc

RUN    apt-get install -y git
# RUN apt-get install python-tk python3-tk tk-dev

WORKDIR /app
COPY . /app

RUN pip install -e .